import asyncio
import json
from typing import List, Optional
from fastapi import FastAPI, HTTPException, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from sse_starlette.sse import EventSourceResponse

from models import (
    HealthResponse,
    JobCreateRequest,
    JobModel,
    JobCancelResponse,
    OutputFileModel,
    CreateSessionRequest,
    CreateSessionResponse,
    SendMessageRequest
)
from job_manager import JobManager
from agent_adapter import AgentAdapter

app = FastAPI(
    title="Termux CommandDeck Backend",
    description="Localhost CLI execution and automation server for Android Termux CommandDeck",
    version="1.0.0"
)

# Allow local communication from Android app
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

job_manager = JobManager()
agent_adapter = AgentAdapter()

@app.post("/health", response_model=HealthResponse)
async def check_health():
    """Returns status, version, and server timestamp."""
    return HealthResponse(status="ok", version="1.0.0")

@app.post("/jobs", response_model=JobModel)
async def create_job(req: JobCreateRequest):
    """
    Submits a structural job request and returns jobId immediately.
    Never executes arbitrary strings via shell=True.
    """
    try:
        job = job_manager.create_job(
            job_type=req.type,
            executable=req.executable,
            arguments=req.arguments,
            description=req.description or ""
        )
        return job
    except PermissionError as pe:
        raise HTTPException(status_code=403, detail=str(pe))
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.get("/jobs", response_model=List[JobModel])
async def list_jobs():
    """Lists all active and recent jobs."""
    return list(job_manager.jobs.values())

@app.get("/jobs/{job_id}", response_model=JobModel)
async def get_job(job_id: str):
    """Fetches full state and metadata for a specific job."""
    job = job_manager.jobs.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    return job

@app.post("/jobs/{job_id}/cancel", response_model=JobCancelResponse)
async def cancel_job(job_id: str):
    """Cancels a running job process and terminates its process tree."""
    success = job_manager.cancel_job(job_id)
    if not success:
        raise HTTPException(status_code=404, detail="Job not found or already finished")
    return JobCancelResponse(success=True, message=f"Job {job_id} cancelled")

@app.get("/jobs/{job_id}/events")
async def stream_job_events(request: Request, job_id: str):
    """
    Streams live job events over Server-Sent Events (SSE).
    Includes status, progress, stdout, stderr, file discovery, completed, failed, cancelled.
    """
    job = job_manager.jobs.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")

    queue = job_manager.subscribe_events(job_id)

    async def event_generator():
        try:
            # Emit current snapshot first to sync state
            yield {
                "event": "status",
                "data": json.dumps({"status": job.status.value})
            }
            if job.progress > 0:
                yield {
                    "event": "progress",
                    "data": json.dumps({"percent": job.progress, "speed": job.speed, "eta": job.eta})
                }

            while True:
                if await request.is_disconnected():
                    break
                try:
                    event_data = await asyncio.wait_for(queue.get(), timeout=15.0)
                    yield {
                        "event": event_data["event"],
                        "data": json.dumps(event_data["data"])
                    }
                    if event_data["event"] in ["completed", "failed", "cancelled"]:
                        break
                except asyncio.TimeoutError:
                    # Keep-alive heartbeat comment
                    yield {"comment": "ping"}
        finally:
            job_manager.unsubscribe_events(job_id, queue)

    return EventSourceResponse(event_generator())

@app.get("/jobs/{job_id}/files", response_model=List[OutputFileModel])
async def get_job_files(job_id: str):
    """Returns all files generated by this job."""
    job = job_manager.jobs.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    return job.outputFiles

@app.get("/files/{file_id}")
async def download_file(file_id: str):
    """Streams a generated output file to the Android client."""
    # Find matching file in any job
    for job in job_manager.jobs.values():
        for f in job.outputFiles:
            if f.fileId == file_id:
                job_dir = job_manager.get_job_dir(job.jobId)
                path = job_dir / "output" / f.filename
                if path.exists():
                    return FileResponse(
                        path=str(path),
                        filename=f.filename,
                        media_type=f.mimeType
                    )
    raise HTTPException(status_code=404, detail="File not found")

@app.post("/agent/sessions", response_model=CreateSessionResponse)
async def create_agent_session(req: CreateSessionRequest):
    """Creates a new AI Agent conversation session."""
    return agent_adapter.create_session(title=req.title, agent_type=req.agentType or "aider")

@app.post("/agent/sessions/{session_id}/messages")
async def send_agent_message(session_id: str, req: SendMessageRequest):
    """Receives a user query and asynchronously triggers streaming tokens."""
    asyncio.create_task(agent_adapter.handle_message(session_id, req.message))
    return {"status": "processing"}

@app.get("/agent/sessions/{session_id}/events")
async def stream_agent_events(request: Request, session_id: str):
    """Streams AI agent output tokens over SSE."""
    queue = agent_adapter.subscribe(session_id)

    async def event_generator():
        try:
            while True:
                if await request.is_disconnected():
                    break
                try:
                    event_data = await asyncio.wait_for(queue.get(), timeout=20.0)
                    yield {
                        "event": event_data["event"],
                        "data": json.dumps(event_data["data"])
                    }
                    if event_data["event"] in ["complete", "error"]:
                        break
                except asyncio.TimeoutError:
                    yield {"comment": "ping"}
        finally:
            agent_adapter.unsubscribe(session_id, queue)

    return EventSourceResponse(event_generator())

if __name__ == "__main__":
    import uvicorn
    # STRICT MANDATE: Bind only to localhost (127.0.0.1) on port 8080
    uvicorn.run("main:app", host="127.0.0.1", port=8080, log_level="info")
